language: haskell

install:
    # travis-ci currently does not run `cabal update`
    # (see https://github.com/travis-ci/travis-build/pull/91)
    #
    # So we need to do it manually for now...
    - cabal update
    - git clone https://github.com/franckrasolo/pepino && cd pepino && cabal install && cd ..
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure --enable-tests && cabal build && cabal test

notifications:
  email: true
