language: haskell

install:
    - git clone https://github.com/franckrasolo/pepino && cd pepino && cabal install && cd ..
    - cabal install --only-dependencies --enable-tests

script:
    - cabal configure --enable-tests && cabal build && cabal test

notifications:
  email: true
